receivers:
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
  attributes/agent:
    actions:
      - key: logzio_agent_version
        value: v1.0.36
        action: insert
exporters:
  logging:
service:
  pipelines:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address:
