receivers:
processors:
  resourcedetection/system:
    detectors: ["system"]
    system:
      hostname_sources: ["os"]
exporters:
  logging:
service:
  pipelines:
  telemetry:
    logs:
      level: "debug"
    metrics:
      address:
