apiVersion: v1
kind: Pod
metadata:
  name: logzio-metrics-connection-test
spec:
  containers:
    - name: logzio-metrics-connection-test
      image: busybox:latest
      command: ["/bin/sh", "-c"]
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: OnFailure