mac_run:
linux_run:
windows_run: |
  function New-OtelReceiver {
    param (
      [hashtable]$FuncArgs
    )

    $local:LogsType = $FuncArgs.LogsType

    $local:Err = Set-YamlFileFieldValue "$LogzioTempDir\resources\otel\receivers\windowseventlog_application.yaml" '.receiver.windowseventlog/application/NAME.attributes.type' $LogsType
    if ($Err.Count -ne 0) {
      Write-Output "error setting type to windowseventlog/application receiver: $($Err[0])"
      return 2
    }
  }
receiver:
  windowseventlog/application/NAME:
    channel: Application
    attributes:
      type: