receivers:
processors:
  batch:
    send_batch_size: 10000
    timeout: 1s
exporters:
service:
  pipelines:
    logs:
      receivers: []
      exporters: []
    metrics:
      receivers: []
      exporters: []
