receivers:
processors:
  attributes/env_id:
    actions:
    - action: insert
      key: env_id
      value: ${ENV_ID}
connectors: {}
exporters:
  debug:
service:
  pipelines:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: localhost:8888
