transform/application:
  error_mode: ignore
  log_statements:
    - context: log
      statements: 
        - flatten(body["event_data"], depth=1)
        - flatten(body["event_data"], depth=2)
        - replace_all_patterns(body["event_data"], "key", "^data.([0-9A-Za-z]+).", "data_$${1}_") # Transforms 'data.<dynamic_part>.' keys. If <dynamic_part> is not empty, it formats as 'data_0_TargetUserName:"Administrator"'. Otherwise, it appears as 'data_0_:"Administrator"'.
