apiVersion: v1
kind: Pod
metadata:
  name: logzio-metrics-connection-test
spec:
  containers:
  - name: logzio-metrics-connection-test
    image: busybox:latest
    command: [ "/bin/sh", "-c", "telnet listener.logz.io 8053" ]
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: OnFailure