name: Barak
env:
  VALUE_ARRAY_AS_STRING: '*.json'
on: [push]
jobs:
  get-manifest:
    name: Manifest test!
    runs-on: ubuntu-latest
    steps:
      - name: Read aws.json
        id: aws
        uses: juliangruber/read-file-action@v1
        with:
          path: ./manifest/aws.json
      
      - name: Echo aws.json
        run: echo "${{ steps.aws.outputs.content }}"
